HTTP_PAGE_NOT_FOUND_CODE = 404
HTTP_PAGE_NOT_FOUND_HTTP_CODE = 404
HTTP_INTERNAL_SERVER_ERROR_STATUS_CODE = 500
HTTP_INTERNAL_SERVER_ERROR_HTTP_CODE = 500
HTTP_CLIENT_ERROR_STATUS_CODE = 400
HTTP_CLIENT_ERROR_HTTP_CODE = 400
HTTP_FOR_HIDDEN_STATUS_CODE = 403
HTTP_FOR_HIDDEN_HTTP_CODE = 403
HTTP_UN_AUTHORIZATION_STATUS_CODE = 401
HTTP_UN_AUTHORIZATION_HTTP_CODE = 401

HTTP_PAGE_NOT_FOUND_MSG = "ERROR PAGE NOT FOUND"
HTTP_INTERNAL_SERVER_ERROR_MSG = "INTERNAL SERVER ERROR"
HTTP_CLIENT_ERROR_MSG = "ข้อมูลไม่ถูกต้อง"
HTTP_UN_AUTHORIZATION_MSG = "Not Authorization"
HTTP_NOT_VERSION_MSG = "กรุณาระบุ version api ให้ถูกต้อง"