SELECT_TEMPLATE = "<SELECT [remember|understand|implement|analysis]><COLUMN>*|<OPTION><UPPER><FILED_NAME/>[<NAME/>]</UPPER>|<LOWER><FILED_NAME/>[<NAME/>]</LOWER>|<AVG><FILED_NAME/>[<NAME/>]</AVG>|<MIN><FILED_NAME/>[<NAME/>]</MIN>|<MAX><FILED_NAME/>[<NAME/>]</MAX>|<COUNT>*|<FILED_NAME/>[<NAME/>]</COUNT>|<SUM><FILED_NAME/>[<NAME/>]</SUM>|<FILED_NAME><VALUE/>[<NAME/>]</FILED_NAME>|<DISTINCT><FILED_NAME/>[<NAME/>]</DISTINCT></OPTION></COLUMN><TABLE_NAME/>[<OPTION [SEQ]><WHERE><CON>[<PRE>AND|OR</PRE>]<FILED_NAME/><OPERATOR>=|>|<|<>|>=|<=|LIKE|BETWEEN|IN</OPERATOR><VALUE/>[<VALUE2/>][<VALUES/>]</CON></WHERE>|(<GROUPBY><FILED_NAME/></GROUPBY>|<HAVING><CON>[<PRE>AND|OR</PRE>]<FILED_NAME/>|[<AVG/>|<MIN/>|<MAX/>|<COUNT/>|<SUM/>]<OPERATOR>=|<|<>|>|>=|<=|LIKE|BETWEEN</OPERATOR><VALUE/>[<VALUE2/>]</CON><HAVING/>)|<ORDERBY><FILED_NAME/><VALUE>ASC|DESC</VALUE></ORDERBY></OPTION>]</SELECT>"
SELECT_TEMPLATE_AN = "<SELECT [remember|understand|implement|analysis]><COLUMN>*|<OPTION><UPPER><FILED_NAME/>[<NAME/>]</UPPER>|<LOWER><FILED_NAME/>[<NAME/>]</LOWER>|<AVG><FILED_NAME/>[<NAME/>]</AVG>|<MIN><FILED_NAME/>[<NAME/>]</MIN>|<MAX><FILED_NAME/>[<NAME/>]</MAX>|<COUNT>*|<FILED_NAME/>[<NAME/>]</COUNT>|<SUM><FILED_NAME/>[<NAME/>]</SUM>|<FILED_NAME><VALUE/>[<NAME/>]</FILED_NAME>|<DISTINCT><FILED_NAME/>[<NAME/>]</DISTINCT></OPTION></COLUMN><TABLE_NAME/>[<OPTION [SEQ]><WHERE><CON>[<PRE>AND|OR</PRE>]<FILED_NAME/><OPERATOR>=|>|<|<>|>=|<=|LIKE|BETWEEN|IN</OPERATOR><VALUE/>[<VALUE2/>][<VALUES/>]</CON></WHERE>|(<GROUPBY><FILED_NAME/></GROUPBY>|<HAVING><CON>[<PRE>AND|OR</PRE>]<FILED_NAME/>|[<AVG/>|<MIN/>|<MAX/>|<COUNT/>|<SUM/>]<OPERATOR>=|<|<>|>|>=|<=|LIKE|BETWEEN</OPERATOR><VALUE/>[<VALUE2/>]</CON><HAVING/>)</OPTION>]</SELECT>"
SELECT_TEMPLATE_UN = "<SELECT [remember|understand|implement|analysis]><COLUMN>*|<OPTION><UPPER><FILED_NAME/>[<NAME/>]</UPPER>|<LOWER><FILED_NAME/>[<NAME/>]</LOWER>|<AVG><FILED_NAME/>[<NAME/>]</AVG>|<MIN><FILED_NAME/>[<NAME/>]</MIN>|<MAX><FILED_NAME/>[<NAME/>]</MAX>|<COUNT>*|<FILED_NAME/>[<NAME/>]</COUNT>|<SUM><FILED_NAME/>[<NAME/>]</SUM>|<FILED_NAME><VALUE/>[<NAME/>]</FILED_NAME>|<DISTINCT><FILED_NAME/>[<NAME/>]</DISTINCT></OPTION></COLUMN><TABLE_NAME/>[<OPTION [SEQ]><WHERE><CON>[<PRE>AND|OR</PRE>]<FILED_NAME/><OPERATOR>=|>|<|<>|>=|<=|LIKE|BETWEEN|IN</OPERATOR><VALUE/>[<VALUE2/>][<VALUES/>]</CON></WHERE>|<ORDERBY><FILED_NAME/><VALUE>ASC|DESC</VALUE></ORDERBY></OPTION>]</SELECT>"
SELECT_TEMPLATE_RM = "<SELECT [remember|understand|implement|analysis]><COLUMN>*|<OPTION><UPPER><FILED_NAME/>[<NAME/>]</UPPER>|<LOWER><FILED_NAME/>[<NAME/>]</LOWER>|<AVG><FILED_NAME/>[<NAME/>]</AVG>|<MIN><FILED_NAME/>[<NAME/>]</MIN>|<MAX><FILED_NAME/>[<NAME/>]</MAX>|<COUNT>*|<FILED_NAME/>[<NAME/>]</COUNT>|<SUM><FILED_NAME/>[<NAME/>]</SUM>|<FILED_NAME><VALUE/>[<NAME/>]</FILED_NAME>|<DISTINCT><FILED_NAME/>[<NAME/>]</DISTINCT></OPTION></COLUMN><TABLE_NAME/>[<OPTION [SEQ]><WHERE><CON>[<PRE>AND|OR</PRE>]<FILED_NAME/><OPERATOR>=|>|<|<>|>=|<=|LIKE|BETWEEN|IN</OPERATOR><VALUE/>[<VALUE2/>][<VALUES/>]</CON></WHERE></OPTION>]</SELECT>"

INSERT_TEMPLATE = "<INSERT [remember|understand|implement|analysis]><TABLE_NAME/><COLUMN><OPTION><FILED_NAME><VALUE/>[<NAME/>]</FILED_NAME></OPTION></COLUMN><VALUES/></INSERT>"
UPDATE_TEMPLATE = "<UPDATE [remember|understand|implement|analysis]><TABLE_NAME/><VALUES/><WHERE><CON>[<PRE>AND|OR</PRE>]<FILED_NAME/><OPERATOR>=|>|<|<>|>=|<=|LIKE|BETWEEN|IN</OPERATOR><VALUE/>[<VALUE2/>][<VALUES/>]</CON></WHERE></UPDATE>"
DELETE_TEMPLATE = "<DELETE [remember|understand|implement|analysis]><TABLE_NAME/><WHERE><CON>[<PRE>AND|OR</PRE>]<FILED_NAME/><OPERATOR>=|>|<|<>|>=|<=|LIKE|BETWEEN|IN</OPERATOR><VALUE/>[<VALUE2/>][<VALUES/>]</CON></WHERE></DELETE>"
TEMPLATES = {
    'SELECT': {
        'REMEMBER': SELECT_TEMPLATE_RM,
        'UNDERSTAND': SELECT_TEMPLATE_UN,
        'IMPLEMENT': SELECT_TEMPLATE,
        'ANALYSIS': SELECT_TEMPLATE_AN
    },
    'INSERT': {
        'REMEMBER': INSERT_TEMPLATE,
        'UNDERSTAND': INSERT_TEMPLATE,
        'IMPLEMENT': INSERT_TEMPLATE,
        'ANALYSIS': INSERT_TEMPLATE
    },
    'UPDATE': {
        'REMEMBER': UPDATE_TEMPLATE,
        'UNDERSTAND': UPDATE_TEMPLATE,
        'IMPLEMENT': UPDATE_TEMPLATE,
        'ANALYSIS': UPDATE_TEMPLATE
    },
    'DELETE': {
        'REMEMBER': DELETE_TEMPLATE,
        'UNDERSTAND': DELETE_TEMPLATE,
        'IMPLEMENT': DELETE_TEMPLATE,
        'ANALYSIS': DELETE_TEMPLATE
    }
}

OPTION_TEMPLATE = {
    'REMEMBER': '[<OPTION [SEQ]><WHERE><CON>[<PRE>AND|OR</PRE>]<FILED_NAME/><OPERATOR>=|>|<|<>|>=|<=|LIKE|BETWEEN|IN</OPERATOR><VALUE/>[<VALUE2/>][<VALUES/>]</CON></WHERE></OPTION>]',
    'UNDERSTAND': '[<OPTION [SEQ]><WHERE><CON>[<PRE>AND|OR</PRE>]<FILED_NAME/><OPERATOR>=|>|<|<>|>=|<=|LIKE|BETWEEN|IN</OPERATOR><VALUE/>[<VALUE2/>][<VALUES/>]</CON></WHERE>|<ORDERBY><FILED_NAME/><VALUE>ASC|DESC</VALUE></ORDERBY></OPTION>]',
    'IMPLEMENT': '[<OPTION [SEQ]><WHERE><CON>[<PRE>AND|OR</PRE>]<FILED_NAME/><OPERATOR>=|>|<|<>|>=|<=|LIKE|BETWEEN|IN</OPERATOR><VALUE/>[<VALUE2/>][<VALUES/>]</CON></WHERE>|(<GROUPBY><FILED_NAME/></GROUPBY>|<HAVING><CON>[<PRE>AND|OR</PRE>]<FILED_NAME/>|[<AVG/>|<MIN/>|<MAX/>|<COUNT/>|<SUM/>]<OPERATOR>=|<|<>|>|>=|<=|LIKE|BETWEEN</OPERATOR><VALUE/>[<VALUE2/>]</CON><HAVING/>)|<ORDERBY><FILED_NAME/><VALUE>ASC|DESC</VALUE></ORDERBY></OPTION>]',
    'ANALYSIS': '[<OPTION [SEQ]><WHERE><CON>[<PRE>AND|OR</PRE>]<FILED_NAME/><OPERATOR>=|>|<|<>|>=|<=|LIKE|BETWEEN|IN</OPERATOR><VALUE/>[<VALUE2/>][<VALUES/>]</CON></WHERE>|(<GROUPBY><FILED_NAME/></GROUPBY>|<HAVING><CON>[<PRE>AND|OR</PRE>]<FILED_NAME/>|[<AVG/>|<MIN/>|<MAX/>|<COUNT/>|<SUM/>]<OPERATOR>=|<|<>|>|>=|<=|LIKE|BETWEEN</OPERATOR><VALUE/>[<VALUE2/>]</CON><HAVING/>)</OPTION>]'
}

CLAUSES = {
    'string': ['LIKE', 'UPPER', 'LOWER', 'BETWEEN', 'IN'],
    'int': ['MAX', 'MIN', 'LIKE', 'BETWEEN', 'IN'],
    'double': ['MAX', 'MIN', 'LIKE', 'BETWEEN', 'IN'],
    'char': ['LIKE', 'UPPER', 'LOWER', 'BETWEEN', 'IN'],
    'date': ['BETWEEN', 'IN', 'MAX', 'MIN'],
    'dateTime': ['BETWEEN', 'IN', 'MAX', 'MIN'],
    'timestamp': ['BETWEEN', 'IN', 'MAX', 'MIN']
}
