from routes.auth import auth
from routes.user import user
from routes.subject import subject
from routes.sec import sec
from routes.student import student
from routes.exam_db import exam_db
from routes.exam import exam
from routes.test import test
from routes.score import score